// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class aspnet_MembershipAudit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnet_MembershipAudit));
        
        string IMigrationMetadata.Id
        {
            get { return "201603110719123_aspnet_MembershipAudit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
